platform :ios, '12.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

def shared_pods
	pod 'Alamofire', '~> 4.7'
  pod 'SwiftLint'
end

target 'EventyayOrganizer' do
  use_frameworks!
  # Pods for EventyayOrganizer
  pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :commit => 'ea59f7c4d72a4c3a3694042b05d4276e2ffd4e26'
  pod 'M13Checkbox', :git => 'https://github.com/Marxon13/M13Checkbox.git', :branch => 'swift_5'
  pod 'ObjectMapper', '~> 3.4'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'NVActivityIndicatorView'
  shared_pods
end

  target 'EventyayOrganizerUITests' do
    use_frameworks!
  
    shared_pods
end
