// LocalConfig.swift — AUTO-GENERATED by setup.py. Do not edit by hand.
// Re-run `python3 setup.py` from the repo root to update the debug URL.
enum LocalConfig {
    static let debugBaseURL = "http://192.168.100.125:8080/v1"
}
